# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/8"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"

  #
  # Descomentar si estamos destras de un proxy
  #
  #if Vagrant.has_plugin?("vagrant-proxyconf")
  #  config.proxy.http     = "http://192.168.150.17:8080"
  #  config.proxy.https    = "http://192.168.150.17:8080"
  #  config.proxy.no_proxy = "localhost,127.0.0.1"
  #end

  # Mas informacion sobre requerimientos: https://yum.oracle.com/boxes/
  config.vm.define "edx01" do |h|
    h.vm.box = "oraclelinux/8"
    h.vm.hostname = "edx01"
    h.vm.network "private_network", ip: "10.1.100.100"
    h.vm.provision "shell", path: "provisioning-dockers.sh"
    h.vm.provider "virtualbox" do |vb|
      vb.name = "edx01-ol8"
      vb.memory = "4048"
      vb.cpus = 4
    end    
  end
end
